auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 24h
# compactor settings (needed when using boltdb-shipper + filesystem)
compactor:
  # working directory for compactor state
  working_directory: /loki/compactor
  # use the filesystem shared store (matches your storage_config)
  shared_store: filesystem
