apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://cv-prometheus:9090
    isDefault: true
    version: 1
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://cv-loki:3100
    isDefault: false
    version: 1
    editable: false
